### ISSUE TITLE
Comma support for floating points?

### ISSUE THREAD

**Issue by TehMillhouse** [fsmi/odie-client#103]
[ imported from RT ]
Das Eurofeld in der Abrechnungskorrektur sollte als 0.00 als Standardwert
haben. Das hilft dabei zu erkennen, dass ein Punkt als Trennzeichen
gesucht ist und nicht ein Komma (Mit Komma kommt eine Korrektur von 0.00
raus).
Alternative kann man natürlich auch einfach 0,00 auch als validen Wert
angeben, oder es sollte dann zumindest eine Fehlermeldung kommen.

**Comment by Kha** [comment]
c48a199d364f9

**Comment by Kha** [comment]
24afc7d0e214
