### ISSUE TITLE
New Exams are still added to Cart

### ISSUE THREAD

**Issue by dedrone** [fsmi/odie-client#154]
New unchecked exams are shown as added to cart even if they are not. Instead the last selected exam is shown as not in cart even if it is.

**Comment by dedrone** [comment]
![screenshot from 2015-09-25 15 23 09](https://cloud.githubusercontent.com/assets/4119041/10101578/d4e80f4a-6399-11e5-9766-ca39c7a14514.png)

**Comment by Kha** [comment]
Good catch, thanks!
