### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by uscdy** [fsmi/odie-client#175]
The project lacks a license. The first missing license is in the `package.json` file, npm complains at the end of the installation process:
```
npm WARN EPACKAGEJSON odie-client No license field.
```
https://docs.npmjs.com/files/package.json

The other issue is the compiled JavaScript, it is not compatible with LibreJS.
http://www.gnu.org/software/librejs/free-your-javascript.html
You can prepend a boilerplate string using the following shell command:
```
echo -e "License string\n$(cat assets/scripts.js)" > assets/scripts.js
```
I'm not sure how to work around the fact that the script is made of several different scripts with different licenses stitched together.

You should also have a project-wide global license file for everything else.

**Comment by Kha** [comment]
> The other issue is the compiled JavaScript, it is not compatible with LibreJS.

Uhh... I'll pass.

**Comment by uscdy** [comment]
OK, LibreJS is a pain anyway ;) Thanks for your time
