### ISSUE TITLE
change "Anonyme Abgabe"

### ISSUE THREAD

**Issue by sub-path** [fsmi/odie-client#189]
"Anonyme Abgabe" is describing, that you can get your deposit back.
But when somebody do this we can't control the protocol.

So please change "Anonyme Abgabe" to "Pfand spenden"

**Comment by TehMillhouse** [comment]
For obvious reasons, documents uploaded without a name don't show up in the deposit return tab, however, they can still be found in the DB admin as unchecked documents. As for the string in the UI, well...

![screenshot from 2016-04-27 12-47-36](https://cloud.githubusercontent.com/assets/796437/14850000/7ee1eba8-0c76-11e6-95dd-f4cb8691a7f8.png)
