### ISSUE TITLE
lecture column in preselection view should use more grouping

### ISSUE THREAD

**Issue by jduepmeier** [fsmi/odie-client#41]
it would be very nice to see grouping in the lecture column. Maybe group by lecture and show the different dates of the specific lecture.
Example:

Betriebssysteme:
* 2014-12-01
* 2014-06-07
* ...

**Comment by Kha** [comment]
odie-client/next now shows a sorted, de-duplicated list of lectures. For the individual dates, one should probably just open the cart.
