### ISSUE TITLE
incorrect lecture mapping

### ISSUE THREAD

**Issue by Strandtasche** [fsmi/odie-client#47]
If one enters "Grundlagen der Wahrscheinlichkeitstheorie und Statistik für Studierende der Informatik" there are no files there, but if one enters "Wahrscheinlichkeitstheorie" one is send to the files correspondent to "Grundlagen der Wahrscheinlichkeitstheorie und Statistik für Studierende der Informatik".

same goes for "Theoretische Grundlagen der Informatik" and "Theoretische Grundlagen"

**Comment by Kha** [comment]
I guess the original issue was fixed at some point? Anyways, improving the DB is kinda covered by #79.
