### ISSUE TITLE
Saving button beside "Drucken" button

### ISSUE THREAD

**Issue by Indidev** [fsmi/odie-client#48]
Saving preselections as "Fachschaftler" should be enabled.

Use case:
Somebody wants to buy some protocolls, however that person does not have enough money to buy them. Thats why he wants to come back later and buy them.
Saving his selection would avoid a loss of time due to another round of picking out his relevant protocolls.

**Comment by TheMarex** [comment]
This needs some restructuring of the ```cart``` and ```print``` MV.
Current pain points:
* Separate price fields
* Separate name fields (```coverText``` vs ```cart.name```)
