### ISSUE TITLE
checkmark never disappears until page reload

### ISSUE THREAD

**Issue by mars27** [fsmi/odie-client#55]
If you have several jobs in a row, the check mark stays from the first print on and never disappears, so therefore is useless for every job after. Should automatically be removed if you apply any changes such as adding something to cart, deleting something or changing the name of the client.

**Comment by Kha** [comment]
> the check mark stays from the first print on and never disappears
It should be replaced on every new print (i.e. first the loading symbol, then the request result), does this really not happen? Either way, clearing it early when modifying the print job sounds reasonable.

**Comment by mars27** [comment]
yes, that happens - but after the loading symbol is replaced by the checkmark, you cannot see for which print job the check mark stands. When taking cash after clicking on "print", I sometimes wonder afterwards if I had really pressed the button or if I just forgot it...

**Comment by TheMarex** [comment]
I think it would be a good solution to clear the indicator, once the cart or the name field has been changed.
