### ISSUE TITLE
Incorrect print order when printing saved odie selection

### ISSUE THREAD

**Issue by andreas-eberle** [fsmi/odie-client#59]
I selected multiple exams of multiple lectures in odie, saved my configuration with my name, went to the FSMI and asked them to print my saved list of exams. The problem is that the printed exams now have no order at all. Neither the order I selected them (one lecture after another), nor are they sorted by lectures or dates.

I think the printed exams should be printed by lectures first and dates afterwards.

**Comment by Kha** [comment]
Fixed in odie-server/next
