### ISSUE TITLE
Use cookie defined prefix for view links

### ISSUE THREAD

**Issue by JustKiddingCode** [fsmi/odie-client#82]
Instead of using the file:///[links], use a prefix that can be changed by a cookie.
For example, you could then set your cookie to use sftp and support viewing by your laptop.

**Comment by Kha** [comment]
The originally intended way was to use sshfs, but all these ugly hacks will be obsolete either way with the next version, which will serve previews via http.

**Comment by Kha** [comment]
Implemented in 1d3328466
