### ISSUE TITLE
Sort protocols by 'Einpflegedatum'

### ISSUE THREAD

**Issue by chaupow** [fsmi/odie-client#89]
Manchmal kommen Menschen, die bereits Protokolle gekauft haben und schauen möchten, ob es neue gibt. Das Datum der Prüfung und das Datum, wann es eingepflegt wurde sind aber nicht wirklich gleich und dann kann man nicht danach sortieren :(

Das wäre cool!
So cool!

**Comment by TehMillhouse** [comment]
Bisher wird das Einpflegedatum gar nicht in der Datenbank erfasst, für alte Protokolle wird das also sicher nicht umsetzbar sein, aber wenn man das in Zukunft haben will wäre *jetzt* der Zeitpunkt das einzuführen...

Ich mach mal ne entsprechende issue gegen den Server auf.
